"use client"
import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./globals.css";


import path from "path";
import Header from "./components/header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const source_code = Source_Code_Pro({
  // variable: "--font-source-code-pro",
  subsets: ["latin"],
  weight: "400"
})

// because use the client so metadate can not use

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${source_code.className} antialiased`}>
        <div className="flex">
          <div className="w-40">
            <Header />
          </div>

          <main className="flex-1 flex justify-center items-center">
            {children}
          </main>
        </div>

      </body>
    </html>
  );
}
